spring:
  datasource:
    username: root
    password: fang2831016
    url: jdbc:mysql://cdb-1yzvsfly.bj.tencentcdb.com:10006/springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
